(defun help ()
  "Prints the Bogu command cheat sheet."
  (format t "~%===========================================================~%")
  (format t "                       BOGU HELP MENU                        ~%")
  (format t "===========================================================~%~%")
  
  (format t " [ NOTES & BASIC ENTRY ]~%")
  (format t "  <note> <rval> : Enter a note (e.g., c4 q, eb3 .5, f#5 qt)~%")
  (format t "  rst <rval>    : Enter a rest of the specified rhythm.~%")
  (format t "  del <n>       : Delete the last <n> notes and rewind time.~%")
  (format t "  rpt <n>       : Repeat the last <n> notes.~%~%")
  
  (format t " [ SEQUENCES & CHORDS ]~%")
  (format t "  seq <rval> <notes>  : Sequence of notes (e.g., seq q c4 e4 g4)~%")
  (format t "  %                   : Repeat the last evaluated sequence.~%")
  (format t "  poly <rval> <notes> : Enter a chord (preserves global time).~%")
  (format t "  sarp <rval> <sval> <notes> : Sustained arpeggio (rhythm & sustain length).~%~%")
  
  (format t " [ TIME & ENVIRONMENT ]~%")
  (format t "  bpm <n>       : Set beats per minute (Default: 60).~%")
  (format t "  i <n>         : Change active instrument (e.g., i 1, i 2).~%")
  (format t "  where <div>   : Display current measure and beat based on divisor.~%")
  (format t "  reset         : Wipe score and reset all global variables to 0.~%~%")

  (format t " [ DEFINITIONS & PASSAGES ]~%")
  (format t "  defseq <name> <notes> : Define a custom sequence to use later.~%")
  (format t "  defpoly <name> <notes>: Define a custom chord.~%")
  (format t "  seqs / polys          : View saved sequences or chords.~%")
  (format t "  pas                   : Toggle passage recording on/off.~%")
  (format t "  psg <n>               : Play back a recorded passage.~%")
  (format t "  psgs                  : View all recorded passages.~%~%")

  (format t " [ SYSTEM & PLAYBACK ]~%")
  (format t "  save \"name\"      : Save composition to a .bogu and .csd file.~%")
  (format t "  bogu-load \"name\" : Load and evaluate a saved .bogu file.~%")
  (format t "  play \"name\"      : Render and play the saved .csd file.~%")
  (format t "===========================================================~%~%"))
