(in-package :bogu)

(defun help ()
  "Prints the updated Bogu Command Reference."
  (format t "~%===========================================================~%")
  (format t "                  BOGU COMMAND REFERENCE                   ~%")
  (format t "===========================================================~%")
  (format t "~%--- TRANSPORT & TIME ---~%")
  (format t " play              : Plays the built *score* buffer.~%")
  (format t " stop              : Halts standard playback.~%")
  (format t " live-loop [n] [b] : Loops a block [b] every [n] beats (e.g., live-loop bass 4 [ ditty ]).~%")
  (format t " stop-loop [n]     : Stops a specific loop by name, or use 'ALL'.~%")
  (format t " bpm [x]           : Sets Master Tempo to [x].~%")
  (format t " quantize [m]      : Sets launch mode. 'FREE' (instant) or 'EXACT' (waits for beat grid).~%")
  
  (format t "~%--- ARRANGEMENT & TRACKS ---~%")
  (format t " i [x]             : Switches active playhead to Instrument Track [x] (1-16).~%")
  (format t " seq [r] [notes]   : Sequences a list of notes at rhythm [r].~%")
  (format t " poly [r] [notes]  : Plays a list of notes simultaneously at rhythm [r].~%")
  (format t " rst [r]           : Inserts a silent rest of rhythm [r].~%")
  (format t " def [var] [code]  : Saves an AST block to a variable.~%")
  (format t " vars              : Lists all custom variables in memory.~%")

  (format t "~%--- SYNTHESIS & MIXING ---~%")
  (format t " synth [i] [name]  : Loads cartridge [name] (SINE, SAW, PLUCK) into Track [i].~%")
  (format t " reboot            : Flashes hardware and applies 'synth' changes.~%")
  (format t " vol [x]           : Sets Master Velocity (0-100).~%")
  (format t " reverb [x]        : Sets Master Reverb Mix (0-100).~%")
  (format t " transpose [x] [b] : Transposes block [b] by [x] semitones.~%")

  (format t "~%--- SYSTEM ---~%")
  (format t " reset             : Wipes memory, clears loops, resets playheads.~%")
  (format t " save [name]       : Saves history to compositions/[name]/[name].bogu.~%")
  (format t " load [name]       : Loads a saved project.~%")
  (format t " quit              : Exits the REPL.~%")
  (format t "===========================================================~%~%")
  t)
