(in-package :bogu)

(defun help ()
  "Prints the updated Bogu Command Reference."
  (format t "~%===========================================================~%")
  (format t "                  BOGU COMMAND REFERENCE                   ~%")
  (format t "===========================================================~%")
  (format t "~%--- TRANSPORT & TIME ---~%")
  (format t " play              : Plays the built *score* buffer.~%")
  (format t " stop              : Halts standard playback.~%")
  (format t " live-loop [n] [b] : Loops block [b] every [n] beats (e.g., live-loop bass 4 [ ditty ]).~%")
  (format t " stop-loop [n]     : Stops a specific loop by name, or use 'ALL'.~%")
  (format t " bpm [x]           : Sets Master Tempo to [x].~%")
  (format t " quantize [m]      : Sets sync mode. 'FREE' (instant) or 'EXACT' (waits for beat grid).~%")
  (format t " wait [r]          : Advances the internal playhead by rhythm [r] without playing a note.~%")
  (format t " sync              : Fast-forwards all track playheads to match the furthest one.~%")
  (format t " seek [b]          : Teleports the current track's playhead to an absolute beat [b].~%")

  (format t "~%--- ARRANGEMENT & TRACKS ---~%")
  (format t " i [x]             : Switches active playhead to Instrument Track [x] (1-16).~%")
  (format t " seq [r] [notes]   : Sequences a list of notes at rhythm [r].~%")
  (format t " poly [r] [notes]  : Plays a list of notes simultaneously at rhythm [r].~%")
  (format t " sarp [r] [s] [n]  : Sustained arpeggio. Notes hit every [r] but sustain for [s].~%")
  (format t " rst [r]           : Inserts a silent rest of rhythm [r].~%")
  (format t " def [var] [code]  : Saves an AST block to a variable.~%")
  (format t " vars              : Lists all custom variables in memory.~%")
  (format t " cell [r] [block]  : Executes a block but forces the playhead to advance exactly [r] beats.~%")
  (format t " del [n]           : Deletes the last [n] notes from the active track and rewinds.~%")
  (format t " rpt [n] [s]       : Repeats the last [n] notes, optionally starting [s] notes back.~%")

  (format t "~%--- GENERATIVE & ALGORITHMIC ---~%")
  (format t " loop [n] [block]  : Repeats a block [n] times consecutively.~%")
  (format t " chance [p] [a] [b]: % chance to execute block [a], otherwise executes optional block [b].~%")
  (format t " fluid [d] [r] [n] : Scatters [d] random notes from list [n] across an [r] duration.~%")
  (format t " walk [s] [r] [n]  : Takes [s] random adjacent steps through note list [n] at rhythm [r].~%")
  (format t " retro [block]     : Plays a block perfectly backwards.~%")
  (format t " invert [block]    : Inverts the pitch contour of a block around its first note.~%")

  (format t "~%--- SYNTHESIS & MIXING ---~%")
  (format t " synth [i] [name]  : Loads cartridge [name] (SINE, SAW, PLUCK) into Track [i].~%")
  (format t " reboot            : Flashes hardware and applies 'synth' changes.~%")
  (format t " vol [x]           : Instantly sets Master Velocity (0-100) for the active track.~%")
  (format t " pan [x]           : Instantly sets Panning (0=L, 50=C, 100=R).~%")
  (format t " reverb [x]        : Instantly sets Reverb Mix (0-100).~%")
  (format t " sweep [p] [a] [b] [r] : Automates parameter [p] from [a] to [b] over rhythm [r].~%")
  (format t " transpose [x] [b] : Transposes block [b] by [x] semitones.~%")
  (format t " key [t] [m]       : Sets diatonic mode (e.g., key f lydian) or 'key off' for chromatic.~%")
  (format t " bang [i] [n]      : Instantly fires note [n] on track [i] (live DJ tool).~%")

  (format t "~%--- NOTATION & SYSTEM ---~%")
  (format t " engrave [f] [i]   : Renders track [i] (or 'ALL') to a LilyPond PDF named [f].~%")
  (format t " staccato [block]  : Tags a block for staccato playback and engraving.~%")
  (format t " free [block]      : Engraves a block as an unmetered cadenza.~%")
  (format t " reset             : Wipes memory, clears loops, resets playheads.~%")
  (format t " save [name]       : Saves history to compositions/[name]/[name].bogu.~%")
  (format t " load [name]       : Loads a saved project.~%")
  (format t " quit              : Exits the REPL.~%")
  (format t "===========================================================~%~%")
  t)
