 (in-package :bogu)

(defparameter *notes* '((b# . 0) (c . 0)
    (c# . 1) (db . 1)
    (d . 2)
    (d# . 3) (eb . 3)
    (e . 4) (fb . 4)
    (e# . 5) (f . 5)
    (f# . 6) (gb . 6)
    (g . 7)
    (g# . 8) (ab . 8)
    (a . 9)
    (a# . 10) (bb . 10)
    (b . 11) (cb . 11)))

(defparameter *scale-intervals*
  '((MAJOR . (0 2 4 5 7 9 11))
    (MINOR . (0 2 3 5 7 8 10))
    (DORIAN . (0 2 3 5 7 9 10))
    (PHRYGIAN . (0 1 3 5 7 8 10))
    (LYDIAN . (0 2 4 6 7 9 11))
    (MIXOLYDIAN . (0 2 4 5 7 9 10))))

(defun get-note-value (n)
  "Converts note number (semitones above C) to a note symbol."
  (let ((semitone (mod n 12)))
    (car (find-if (lambda (pair) (= (cdr pair) semitone)) *notes*))))

(defun get-note-number (v)
  "Converts note symbol to a note number. Safely throws an error if the note is missing."
  (let ((found (assoc v *notes*)))
    (if found
        (cdr found)
        (error "Music Math Error: The pitch '~A' is not defined in the *notes* dictionary." v))))

(defun rtm (rval)
  "Returns rhythm quantity for corresponding rhythm symbol. If given a number, it simply returns that number."
  (cond ((numberp rval) rval)
	((eq 'q rval) 1.0)
	((eq 'e rval) 0.5)
	((eq 's rval) 0.25)
	((eq 'h rval) 2.0)
	((eq 'w rval) 4.0)
	((eq 't rval) 0.125)
	((eq 'q. rval) 1.5)
	((eq 'q.. rval) 1.75)
	((eq 'e. rval) 0.75)
	((eq 'e.. rval) 0.875)
	((eq 's. rval) 0.375)
	((eq 's.. rval) 0.4375)
	((eq 'h. rval) 3.0)
	((eq 'h.. rval) 3.5)
	((eq 'qt rval) (/ 2.0 3.0))
	((eq 'et rval) (/ 1.0 3.0))
	((eq 'st rval) (/ 0.5 3.0))
	((eq 'tt rval) (/ 0.25 3.0))
	((eq 'ht rval) (/ 4.0 3.0))
	((eq 'qq rval) (/ 4.0 5.0))
	((eq 'eq rval) (/ 2.0 5.0))
	((eq 'sq rval) (/ 1 5.0))
	((eq 'tq rval) (/ 0.5 5.0))
	((eq 'hq rval) (/ 8.0 5.0))))
