;; stdlib/commands.lisp

(in-package :bogu)

;; =============================================================================
;; 1. SEQUENCING & COMBINATORICS
;; =============================================================================

(def-bogu-cmd SEQ (:rhythm-optional &rest :any) (args)
  "Generates a sequential list of events. If rhythm is provided, it scales each step to fit exactly into that rhythm."
  (let* ((expanded (expand-vars args))
         (rhythm (if (and (atom (car expanded)) (numberp (rtm (car expanded)))) (rtm (car expanded)) nil))
         (nodes (smart-unwrap (if rhythm (cdr expanded) expanded)))
         (master-events nil)
         (local-cursor 0.0))
    
    (let* ((nodes-list (if (listp nodes) nodes (list nodes)))
           (evaluated-stream (execute-ast nodes-list)))
      
      (if (null rhythm)
          evaluated-stream
          (let ((groups (group-events-by-time evaluated-stream)))
            (dolist (group groups)
              (let ((block-len 0.0))
                (dolist (e group)
                  (setf block-len (max block-len (or (getf e :written-dur) 0.0))))
                (when (<= block-len 0.0) (setf block-len 1.0))
                
                (let ((scale-factor (/ rhythm block-len)))
                  (dolist (e group)
                    (let ((new-e (copy-list e)))
                      (setf (getf new-e :time) local-cursor)
                      (when (getf new-e :written-dur)
                        (setf (getf new-e :written-dur) (* (getf new-e :written-dur) scale-factor)))
                      (when (getf new-e :dur)
                        (setf (getf new-e :dur) (* (getf new-e :dur) scale-factor)))
                      (push new-e master-events))))
                (incf local-cursor rhythm)))
            (reverse master-events))))))

(def-bogu-cmd POLY (:rhythm-optional &rest :any) (args)
  "Simultaneous evaluation. Geometrically collapses all elements vertically to local time 0.0."
  (let* ((expanded (expand-vars args))
         (rhythm (if (and (atom (car expanded)) (numberp (rtm (car expanded)))) (rtm (car expanded)) nil))
         (nodes (smart-unwrap (if rhythm (cdr expanded) expanded)))
         (nodes-list (if (listp nodes) nodes (list nodes)))
         (master-events nil))
    (dolist (node nodes-list)
      (let ((evaluated-block (execute-ast (list node))))
        (dolist (e evaluated-block)
          (let ((new-e (copy-list e)))
            (when rhythm 
              (setf (getf new-e :written-dur) rhythm)
              (when (getf new-e :dur) (setf (getf new-e :dur) rhythm)))
            (setf (getf new-e :time) 0.0) 
            (push new-e master-events)))))
    (reverse master-events)))

(def-bogu-cmd SIM (&rest :any) (args)
  "Parallel execution. Evaluates multiple blocks simultaneously at time 0.0."
  (let* ((expanded (expand-vars args))
         (master-events nil))
    (dolist (block expanded)
      (let ((evaluated-block (execute-ast (list block))))
        (setf master-events (append master-events (mapcar #'copy-list evaluated-block)))))
    (stable-sort master-events #'< :key (lambda (x) (getf x :time)))))

(def-bogu-cmd CELL (:rhythm :ast) (args)
  "A strict time-window. Evaluates a block, truncates anything that bleeds over both musically and acoustically."
  (let* ((expanded (expand-vars args))
         (cell-duration (rtm (car expanded)))
         (block (cadr expanded))
         (evaluated-block (execute-ast (list block)))
         (master-events nil))
    (dolist (e evaluated-block)
      (when (< (getf e :time) cell-duration)
        (let ((new-e (copy-list e)))
          (unless (getf new-e :dur) (setf (getf new-e :dur) (or (getf new-e :written-dur) 0.1)))
          (when (> (+ (getf new-e :time) (getf new-e :written-dur)) cell-duration)
            (setf (getf new-e :written-dur) (max 0.0 (- cell-duration (getf new-e :time)))))
          (when (> (+ (getf new-e :time) (getf new-e :dur)) cell-duration)
            (setf (getf new-e :dur) (max 0.0 (- cell-duration (getf new-e :time)))))
          (push new-e master-events))))
    (push (list :type :note :pitch-symbol 'RST :time cell-duration :written-dur 0.0) master-events)
    (reverse master-events)))

(def-bogu-cmd WAIT (:rhythm-optional) (args)
  "Generates a pure rest of the specified duration. Defaults to 1.0 (Q)."
  (let* ((expanded (expand-vars args))
         (dur (if expanded (rtm (car expanded)) 1.0)))
    (list (make-rest-event 0.0 dur))))

(def-bogu-cmd MAP-CONTROL (:symbol :number :ast) (args)
  "Converts a musical phrase into a control envelope."
  (let* ((param-id (resolve-param-id (car args)))
         (duration (rtm (cadr args)))
         (phrase (execute-ast (list (caddr args))))
         (master-events nil)
         (num-notes (length phrase)))
    (if (= num-notes 0)
        nil
        (let ((step-size (/ duration num-notes)))
          (dotimes (i num-notes)
            (let* ((event (nth i phrase))
                   (pch (getf event :pch))
                   (normalized-val (if pch (clamp (/ (- pch 7.0) 3.0) 0.0 1.0) 0.5)))
              (push (make-control-event param-id normalized-val normalized-val (* i step-size) step-size)
                    master-events)))
          (reverse master-events)))))

(defun clamp (val min max)
  (max min (min max val)))

;; =============================================================================
;; 2. GENERATIVE & ALEATORIC ENGINES
;; =============================================================================

(def-bogu-cmd SARP (:rhythm :rhythm &rest :any) (args)
  (let* ((expanded (expand-vars args))
         (r (rtm (car expanded)))   
         (s (rtm (cadr expanded)))  
         (nodes (smart-unwrap (cddr expanded)))
         (len (length nodes))
         (local-cursor 0.0)
         (master-events nil))         
    (dotimes (i len)
      (let ((node (nth i nodes)))        
        (let ((evaluated-block (execute-ast (list node)))
              (physics-dur (max 0.1 (- s (* r i)))))            
          (dolist (e evaluated-block)
            (let ((new-e (copy-list e)))
              (setf (getf new-e :time) (+ local-cursor (getf e :time)))
              (setf (getf new-e :written-dur) r)
              (setf (getf new-e :dur) physics-dur) 
              (push new-e master-events)))))
      (incf local-cursor r))
    (push (list :type :note :pitch-symbol 'RST :time (max s local-cursor) :written-dur 0.0) master-events)
    (reverse master-events)))

(def-bogu-cmd FLUID (:number :rhythm &rest :any) (args)
  (let* ((expanded (expand-vars args))
         (density (if (numberp (car expanded)) (car expanded) (parse-integer (string (car expanded)))))
         (r (rtm (cadr expanded)))
         (nodes (smart-unwrap (cddr expanded)))
         (len (length nodes))
         (master-events nil))
    (dotimes (i density)
      (let* ((random-node (nth (random len) nodes))
             (random-offset (* r (/ (random 1000) 1000.0))))
        (let ((evaluated-node (execute-ast (list random-node))))
          (dolist (e evaluated-node)
            (let ((new-e (copy-list e)))
              (setf (getf new-e :time) (+ random-offset (getf e :time)))
              (when (> (+ (getf new-e :time) (getf new-e :written-dur)) r)
                (setf (getf new-e :written-dur) (max 0.0 (- r (getf new-e :time)))))
              (when (getf new-e :dur)
                (when (> (+ (getf new-e :time) (getf new-e :dur)) r)
                  (setf (getf new-e :dur) (max 0.0 (- r (getf new-e :time))))))
              (when (> (getf new-e :written-dur) 0)
                (push new-e master-events)))))))
    (push (list :type :note :pitch-symbol 'RST :time r :written-dur 0.0) master-events)
    (reverse master-events)))

(def-bogu-cmd WALK (:number :rhythm &rest :any) (args)
  (let* ((expanded (expand-vars args))
         (steps (if (numberp (car expanded)) (car expanded) (parse-integer (string (car expanded)))))
         (r (rtm (cadr expanded)))
         (nodes (smart-unwrap (cddr expanded)))
         (len (length nodes))
         (current-idx (random len))
         (local-cursor 0.0)
         (master-events nil))
    (dotimes (i steps)
      (let ((node (nth current-idx nodes)))
        (let ((evaluated-node (execute-ast (list node))))
          (dolist (e evaluated-node)
            (let ((new-e (copy-list e)))
              (setf (getf new-e :time) (+ local-cursor (getf e :time)))
              (setf (getf new-e :written-dur) r)
              (push new-e master-events)))))
      (incf local-cursor r)
      (let ((step (- (random 3) 1)))
        (setf current-idx (+ current-idx step))
        (setf current-idx (max 0 (min (- len 1) current-idx)))))
    (reverse master-events)))

(def-bogu-cmd CHANCE (:number :ast) (args)
  (let* ((expanded (expand-vars args))
         (probability (car expanded))
         (music-block (cadr expanded))
         (evaluated-stream (execute-ast (list music-block)))
         (filtered-stream nil))
    (dolist (event evaluated-stream)
      (when (<= (/ (random 100) 100.0) probability)
        (push event filtered-stream)))
    (reverse filtered-stream)))

(def-bogu-cmd CHOOSE (:number :ast :ast-optional) (args)
  (let* ((expanded (expand-vars args))
         (probability (car expanded))
         (block-a (cadr expanded))
         (block-b (caddr expanded)))
    (if (<= (/ (random 100) 100.0) probability)
        (execute-ast (list block-a))
        (if block-b (execute-ast (list block-b)) nil))))

(def-bogu-cmd BEATS (&rest :any) (args)
  (let* ((expanded (expand-vars args))
         (rhythms (smart-unwrap expanded))
         (r-list (if (listp rhythms) rhythms (list rhythms)))
         (master-events nil)
         (local-cursor 0.0))
    (dolist (r r-list)
      (let ((dur (rtm r)))
        (push (list :type :note :pitch-symbol 'C :octave 4 :time local-cursor :written-dur dur :dur dur :instr *current-instrument*) master-events)
        (incf local-cursor dur)))
    (reverse master-events)))

(def-bogu-cmd TREAD (:number :ast :ast) (args)
  (let* ((expanded (expand-vars args))
         (start-idx (car expanded))
         (intervals (flatten (cadr expanded))) 
         (int-list (if (listp intervals) intervals (list intervals)))
         (pool (smart-unwrap (caddr expanded)))
         (pool-len (length pool))
         (master-events nil)
         (current-idx start-idx)
         (local-cursor 0.0))
    (let* ((first-sym (nth (mod current-idx pool-len) pool))
           (first-node (execute-ast (list first-sym))))
      (dolist (e first-node)
        (let ((new-e (copy-list e)))
          (setf (getf new-e :time) local-cursor)
          (setf (getf new-e :written-dur) 1.0)
          (setf (getf new-e :dur) 1.0)
          (push new-e master-events)))
      (incf local-cursor 1.0))
    (dolist (step int-list)
      (incf current-idx (if (numberp step) step (parse-integer (string step))))
      (let* ((pitch-sym (nth (mod current-idx pool-len) pool))
             (evaluated-node (execute-ast (list pitch-sym))))
        (dolist (e evaluated-node)
          (let ((new-e (copy-list e)))
            (setf (getf new-e :time) local-cursor)
            (setf (getf new-e :written-dur) 1.0)
            (setf (getf new-e :dur) 1.0)
            (push new-e master-events)))
        (incf local-cursor 1.0)))
    (reverse master-events)))

;; =============================================================================
;; 3. TREE TRANSFORMERS & MATH
;; =============================================================================

(def-bogu-cmd AUGMENT (:number :ast) (args)
  (let* ((expanded (expand-vars args))
         (factor (float (car expanded)))
         (child-block (execute-ast (cdr expanded)))
         (master-events nil))
    (dolist (e child-block)
      (let ((new-e (copy-list e)))
        (setf (getf new-e :time) (* (getf new-e :time) factor))
        (when (getf new-e :written-dur)
          (setf (getf new-e :written-dur) (* (getf new-e :written-dur) factor)))
        (when (getf new-e :dur)
          (setf (getf new-e :dur) (* (getf new-e :dur) factor)))
        (push new-e master-events)))
    (reverse master-events)))

(def-bogu-cmd TRANSPOSE (:number :ast) (args)
  "Tags nodes with a transpose offset. Handled Diatonically by the Committer if a KEY is set."
  (let* ((expanded (expand-vars args))
         (offset (if (numberp (car expanded)) (car expanded) (parse-integer (string (car expanded)))))
         (body (cdr expanded))
         (safe-body (if (and (listp body) (listp (car body))) body (list body)))
         (raw-events (execute-ast safe-body)))
    
    (mapcar (lambda (event)
              (if (eq (getf event :type) :note)
                  (let* ((new-event (copy-list event))
                         (current-offset (or (getf new-event :transpose) 0)))
                    (setf (getf new-event :transpose) (+ current-offset offset))
                    new-event)
                  (copy-list event)))
            raw-events)))

(defparameter *pc-to-note* #(C DB D EB E F GB G AB A BB B))

(def-bogu-cmd INVERT (:ast) (args)
  "Inverts pitches. If a KEY is active on the track, inverts diatonically around scale degrees. Otherwise, chromatically."
  (let* ((expanded (expand-vars args))
         (block (car expanded))
         (evaluated-stream (execute-ast (list block)))
         (first-note (find-if (lambda (x) (eq (getf x :type) :note)) evaluated-stream))
         (trk (get-current-track))
         (scale-pitches (get-scale-pitches (track-key trk))))
    
    (if (null first-note)
        evaluated-stream 
        
        (if scale-pitches
            ;; --- 1. DIATONIC INVERSION ---
            (let* ((axis-sym (getf first-note :pitch-symbol))
                   (axis-oct (getf first-note :octave))
                   (axis-idx (pitch-to-diatonic-index axis-sym axis-oct scale-pitches)))
              (mapcar (lambda (event)
                        (if (eq (getf event :type) :note)
                            (let* ((new-event (copy-list event))
                                   (sym (getf new-event :pitch-symbol))
                                   (oct (getf new-event :octave)))
                              (unless (or (eq sym 'R) (eq sym 'RST))
                                (let ((curr-idx (pitch-to-diatonic-index sym oct scale-pitches)))
                                  (if (and axis-idx curr-idx)
                                      (let* ((diff (- curr-idx axis-idx))
                                             (new-idx (- axis-idx diff)))
                                        (multiple-value-bind (new-sym new-oct) (diatonic-index-to-pitch new-idx scale-pitches)
                                          (setf (getf new-event :pitch-symbol) new-sym)
                                          (setf (getf new-event :octave) new-oct)))
                                      ;; Chromatic Fallback for out-of-scale passing tones
                                      (let* ((axis-st (+ (* axis-oct 12) (cdr (assoc axis-sym *notes*))))
                                             (curr-st (+ (* oct 12) (cdr (assoc sym *notes*))))
                                             (diff (- curr-st axis-st))
                                             (new-st (- axis-st diff)))
                                        (setf (getf new-event :pitch-symbol) (aref *pc-to-note* (mod new-st 12)))
                                        (setf (getf new-event :octave) (floor new-st 12))))))
                              new-event)
                            (copy-list event)))
                      evaluated-stream))
            
            ;; --- 2. CHROMATIC INVERSION (Original) ---
            (let* ((axis-sym (getf first-note :pitch-symbol))
                   (axis-oct (getf first-note :octave))
                   (axis-semitone (+ (* axis-oct 12) (cdr (assoc axis-sym *notes*)))))
              (mapcar (lambda (event)
                        (if (eq (getf event :type) :note)
                            (let* ((new-event (copy-list event))
                                   (sym (getf new-event :pitch-symbol))
                                   (oct (getf new-event :octave)))
                              (unless (or (eq sym 'R) (eq sym 'RST))
                                (let* ((current-semitone (+ (* oct 12) (cdr (assoc sym *notes*))))
                                       (diff (- current-semitone axis-semitone))
                                       (new-semitone (- axis-semitone diff))
                                       (new-oct (floor new-semitone 12))
                                       (new-pc (mod new-semitone 12))
                                       (new-sym (aref *pc-to-note* new-pc)))
                                  (setf (getf new-event :pitch-symbol) new-sym)
                                  (setf (getf new-event :octave) new-oct)))
                              new-event)
                            (copy-list event)))
                      evaluated-stream))))))

(def-bogu-cmd RETRO (:ast) (args)
  (let* ((expanded (expand-vars args))
         (block (car expanded))
         (evaluated-stream (execute-ast (list block)))
         (max-time 0.0))
    (dolist (e evaluated-stream)
       (setf max-time (max max-time (+ (getf e :time) (getf e :written-dur)))))
    (stable-sort (mapcar (lambda (e)
                           (let ((new-e (copy-list e)))
                             (setf (getf new-e :time) (- max-time (+ (getf e :time) (getf e :written-dur))))
                             new-e))
                         evaluated-stream)
                 #'< :key (lambda (x) (getf x :time)))))

(def-bogu-cmd RPT (:number :ast) (args)
  (let* ((expanded (expand-vars args))
         (iterations (car expanded))
         (body (cadr expanded))
         (blueprint-events (execute-ast (list body)))
         (master-events nil)
         (local-cursor 0.0)
         (blueprint-len 0.0))
    (dolist (e blueprint-events)
      (setf blueprint-len (max blueprint-len (+ (getf e :time) (getf e :written-dur)))))
    (dotimes (i iterations)
      (dolist (e blueprint-events)
        (let ((new-event (copy-list e)))
          (setf (getf new-event :time) (+ local-cursor (getf e :time)))
          (push new-event master-events)))
      (incf local-cursor blueprint-len))
    (reverse master-events)))

(def-bogu-cmd STACCATO (:number :ast) (args)
  (let* ((expanded (expand-vars args))
         (percent (/ (float (car expanded)) 100.0))
         (child-block (execute-ast (cdr expanded)))
         (master-events nil))
    (dolist (e child-block)
      (let ((new-e (copy-list e)))
        (when (eq (getf new-e :type) :note)
          (let ((current-dur (or (getf new-e :dur) (getf new-e :written-dur))))
            (setf (getf new-e :dur) (* current-dur percent))))
        (push new-e master-events)))
    (reverse master-events)))

(def-bogu-cmd LOOP (:number :ast) (args)
  (let* ((expanded (expand-vars args))
         (iterations (car expanded))
         (body (cadr expanded))
         (combined-result nil))
    (dotimes (i iterations)
      (setf combined-result (append combined-result (execute-ast body))))
    combined-result))

(def-bogu-cmd EVOLVE (:number :ast) (args)
  "Applies all registered parameter-less L-System rules to the AST 'N' times, then evaluates."
  (let* ((expanded (expand-vars args))
         (generations (car expanded))
         (seed (cadr expanded)))
    (dotimes (i generations)
      (setf seed (flatten (mapcar (lambda (sym)
                                    (let ((rule (and (symbolp sym) (gethash sym *rewrite-rules*))))
                                      (if (and rule (null (getf rule :vars)))
                                          (getf rule :transform)
                                          sym)))
                                  seed))))
    (execute-ast seed)))

(def-bogu-cmd ZIP (&rest :any) (args)
  "N-Dimensional Combinatoric Zipper.
   Block 1: Rhythm (Time & Duration)
   Block 2: Pitch (Pitch & Octave)
   Block 3: Dynamics (Velocity)"
  (let* ((expanded (expand-vars args))
         (blocks (mapcar (lambda (b) (execute-ast (list b))) expanded))
         (groups-list (mapcar #'group-events-by-time blocks))
         (master-rhythm-groups (car groups-list))
         (len-rhythm (length master-rhythm-groups))
         (master-events nil))

    (when (> len-rhythm 0)
      (dotimes (i len-rhythm)
        (let* ((step-rhythm (nth i master-rhythm-groups))
               (rhythm-source (car step-rhythm))) 

          (let* ((pitch-groups (if (> (length groups-list) 1) (nth 1 groups-list) master-rhythm-groups))
                 (len-pitch (length pitch-groups))
                 (step-pitch (if (> len-pitch 0) (nth (mod i len-pitch) pitch-groups) nil)))

            (dolist (event-p step-pitch)
              (let ((new-event (copy-list event-p)))
                ;; 1. Inherit Time & Grid Duration
                (setf (getf new-event :time) (getf rhythm-source :time))
                (when (eq (getf rhythm-source :type) :note)
                  (setf (getf new-event :dur) (getf rhythm-source :dur))
                  (setf (getf new-event :written-dur) (getf rhythm-source :written-dur)))

                ;; 2. Inherit Velocity if a 3rd block is present
                (when (> (length groups-list) 2)
                  (let* ((vel-groups (nth 2 groups-list))
                         (len-vel (length vel-groups)))
                    (when (> len-vel 0)
                      (let* ((step-vel (nth (mod i len-vel) vel-groups))
                             (vel-source (car step-vel)))
                        (when (and vel-source (getf vel-source :vel))
                          (setf (getf new-event :vel) (getf vel-source :vel)))))))

                (push new-event master-events)))))))
    (reverse master-events)))

;; =============================================================================
;; 4. LOGIC, STATE & VARIABLES
;; =============================================================================

(def-bogu-cmd DEF (:symbol &rest :any) (args)
  (let* ((var-name (car args))
         (stored-ast (smart-unwrap (cdr args))))
    (setf (gethash var-name *vars*) stored-ast)
    nil))

(def-bogu-cmd I (:number) (args)
  (setf *current-instrument* (car (expand-vars args)))
  nil)

(def-bogu-cmd KEY (:symbol :symbol-optional) (args)
  (let* ((expanded (expand-vars args))
         (trk (get-current-track)))
    (if (or (null expanded) (eq (car expanded) 'OFF) (eq (car expanded) 'NIL))
        (setf (track-key trk) nil) 
        (setf (track-key trk) (list (car expanded) (cadr expanded))))
    nil))

(def-bogu-cmd IF (:any :symbol :any :ast :ast-optional) (args)
  (let* ((cond-args (subseq args 0 3))
         (expanded-cond (expand-vars cond-args))
         (val1 (car expanded-cond))
         (op-sym (cadr expanded-cond))
         (val2 (caddr expanded-cond))
         (op-fn (cond ((eq op-sym '=) #'=) ((eq op-sym '>) #'>) ((eq op-sym '<) #'<)
                      ((eq op-sym '>=) #'>=) ((eq op-sym '<=) #'<=) ((eq op-sym '!=) #'/=) (t nil)))
         (then-branch (nth 3 args))
         (else-branch (nth 4 args)))
    (if (and op-fn (numberp val1) (numberp val2))
        (if (funcall op-fn val1 val2)
            (execute-ast (list then-branch))
            (when else-branch (execute-ast (list else-branch))))
        (format t "~%[Logic Error] Invalid IF syntax.~%"))))

(def-bogu-cmd CLEF (:symbol) (args)
  (let* ((expanded (expand-vars args))
         (c (string-downcase (string (car expanded))))
         (trk (get-current-track)))
    (setf (track-clef trk) c))
  nil)

(def-bogu-cmd BREAK () (args)
  (list (list :type :meta :subtype :line-break :time 0.0 :written-dur 0.0 :dur 0.0)))

;; =============================================================================
;; 5. MIXER & AUTOMATION
;; =============================================================================

(defmacro def-mixer-cmd (name param-id)
  `(def-bogu-cmd ,name (:number) (args)
     (let* ((expanded (expand-vars args))
            (val (/ (float (car expanded)) 100.0)))
       (osc-control *current-instrument* ,param-id 0.01 val val)
       (list (list :type :control :time 0.0 :written-dur 0.0 :dur 0.01 :param ,param-id :start val :end val :instr *current-instrument*)))))

(def-mixer-cmd VOL 1)
(def-mixer-cmd PAN 2)
(def-mixer-cmd REVERB 3)
(def-mixer-cmd FLT 4)

(def-bogu-cmd SWEEP (:symbol :number :number &rest :any) (args)
  (let* ((expanded (expand-vars args))
         (param-input (car expanded))
         (start (/ (float (cadr expanded)) 100.0))
         (end (/ (float (caddr expanded)) 100.0))
         (raw-target (cdddr expanded))
         ;; Extract target intelligently: ignore leading numbers if an AST is present
         (clean-target (remove-if #'numberp raw-target))
         (target (if clean-target clean-target raw-target))
         (param-str (string-upcase (string param-input)))
         (param-id (cond ((member param-str '("VOL" "V") :test #'string=) 1)
                         ((member param-str '("PAN" "P") :test #'string=) 2)
                         ((member param-str '("REVERB" "RVB") :test #'string=) 3)
                         ((member param-str '("FLT" "F") :test #'string=) 4)
                         (t nil))))
    (if (null param-id)
        (progn (format t "~%[SWEEP ERROR] Unknown parameter '~A'. Use VOL, PAN, RVB, or FLT.~%" param-input) nil)
        (if (and target (not (and (= (length target) 1) (numberp (car target)))))
            (let* ((child-events (execute-ast target))
                   (grid-len 0.0))
              (dolist (e child-events)
                (setf grid-len (max grid-len (+ (getf e :time) (or (getf e :written-dur) 0.0)))))
              (cons (list :type :control :time 0.0 :written-dur grid-len :dur grid-len 
                          :param param-id :start start :end end :instr *current-instrument*)
                    child-events))
            (let ((dur (if target (float (car target)) 4.0))) 
               (list (list :type :control :time 0.0 :written-dur 0.0 :dur dur 
                           :param param-id :start start :end end :instr *current-instrument*)))))))

;; =============================================================================
;; 6. LIVE-LOOPING & EXECUTION THREADS
;; =============================================================================

(def-bogu-cmd REBOOT () (args)
  (reboot-audio-server))

(def-bogu-cmd DELAY (:number-optional) (args)
  (sleep (if args (car (expand-vars args)) 1.0))
  nil)

(def-bogu-cmd LIVE-LOOP (:symbol :rhythm-optional :ast) (args)
  (let* ((expanded (expand-vars args))
         (name (car expanded))
         (instr-id *current-instrument*)
         (has-padding (and (cadr expanded) (atom (cadr expanded)) (numberp (rtm (cadr expanded)))))
         (padding-beats (if has-padding (rtm (cadr expanded)) 0.0))
         (block (if has-padding (caddr expanded) (cadr expanded))))
    
    (setf (gethash name *live-loops*) block)
    (format t "~%[LOOP] Armed live-loop '~A' (Auto-size + ~A beats padding).~%" name padding-beats)
    
    (let ((existing-thread (gethash name *loop-threads*)))
      (unless (and existing-thread (sb-thread:thread-alive-p existing-thread))
        (setf (gethash name *loop-threads*)
              (sb-thread:make-thread
               (lambda ()
                 (block thread-execution
                   (handler-case 
                       (let ((next-loop-start-time (get-internal-real-time)))
                         (loop
                           (let ((current-block (gethash name *live-loops*)))
                             (unless current-block 
                               (return-from thread-execution))
                             
                             (let ((*score* '())
                                   (*tracks* (clone-tracks-for-sandbox))
                                   (*current-instrument* instr-id))
                               
                               (commit current-block)
                               (setf *score* (sort *score* #'< :key (lambda (x) (getf x :time))))
                               
                               (let* ((measured-beats (track-playhead (get-current-track)))
                                      (current-bpm (if *bpm* (car *bpm*) 60.0))
                                      (sec-per-beat (float (/ 60.0 current-bpm))))
                                 
                                 (dolist (event *score*)
                                   (let* ((offset-ms (round (* (* (getf event :time) sec-per-beat) internal-time-units-per-second)))
                                          (target-ms (+ next-loop-start-time offset-ms)))
                                     
                                     (loop while (< (get-internal-real-time) target-ms) do
                                       (unless (gethash name *live-loops*)
                                         (return-from thread-execution))
                                       (sleep 0.001))
                                     
                                     (if (eq (getf event :type) :note)
                                         (osc-play (getf event :instr) (* (getf event :dur) sec-per-beat) (getf event :pch) (getf event :vel))
                                         (osc-control (getf event :instr) (getf event :param) (* (getf event :dur) sec-per-beat) (getf event :start) (getf event :end)))))
                                 
                                 (let* ((total-loop-beats (+ measured-beats padding-beats))
                                        (loop-dur-ms (round (* (* total-loop-beats sec-per-beat) internal-time-units-per-second))))
                                   
                                   (incf next-loop-start-time loop-dur-ms)
                                   (loop while (< (get-internal-real-time) next-loop-start-time) do
                                     (unless (gethash name *live-loops*)
                                       (return-from thread-execution))
                                     (sleep 0.001))))))))
                     (error (e) (format t "~%[LOOP ERROR] ~A~%" e)))))
               :name (format nil "bogu-loop-~A" name)))))
    nil))

(def-bogu-cmd STOP-LOOP (:symbol) (args)
  (let ((name (car (expand-vars args))))
    (if (eq name 'ALL)
        (progn
          (clrhash *live-loops*)   
          (clrhash *loop-threads*) 
          (format t "~%[LOOP] Disarmed all loops. Awaiting graceful thread exits...~%"))
        (if (gethash name *live-loops*)
            (progn
              (remhash name *live-loops*)   
              (remhash name *loop-threads*) 
              (format t "~%[LOOP] Disarmed loop '~A'.~%" name))
            (format t "~%[LOOP Error] Loop '~A' is not running.~%" name)))
    nil))

;; =============================================================================
;; 7. NOTATION & EXPORT
;; =============================================================================

(def-bogu-cmd ENGRAVE (:symbol :any) (args)
  (let* ((expanded-args (expand-vars args))
         (filename (car expanded-args))
         (instr (cadr expanded-args)))
    (if (and filename instr)
        (bogu->ly (string-downcase (string filename)) instr)
        (format t "~%[Syntax Error] engrave requires a filename and a track number.~%"))))

;; =============================================================================
;; 8. TIMELINE & TRACK STATE MANAGEMENT
;; =============================================================================

(defun clear-score-only ()
  (clrhash *live-loops*)   
  (clrhash *loop-threads*) 
  (setf *score* '())
  (clrhash *tracks*)
  (setf *master-epoch* nil)
  (format t "~%[SYSTEM] Score cleared. Live-loops signaled to terminate safely. Variables preserved.~%"))

(def-bogu-cmd CLEAR () (args)
  (clear-score-only)
  nil)

(defun ensure-track (id)
  (or (gethash id *tracks*)
      (setf (gethash id *tracks*) (make-track :id id))))

(defun get-current-track ()
  (ensure-track *current-instrument*))

(defun clone-tracks-for-sandbox ()
  (let ((new-ht (make-hash-table)))
    (maphash (lambda (k v)
               (setf (gethash k new-ht)
                     (make-track :id (track-id v)
                                 :playhead 0.0  
                                 :transpose-offset (track-transpose-offset v)
                                 :velocity (track-velocity v)
                                 :articulation (track-articulation v)
                                 :key (track-key v)
                                 :clef (track-clef v))))
             *tracks*)
    new-ht))

(defun current-time ()
  (track-playhead (get-current-track)))

(defun set-current-time (time)
  (setf (track-playhead (get-current-track)) (float time)))

(defun advance-time (amount)
  (incf (track-playhead (get-current-track)) (float amount)))

(defun seek (beat)
  (let ((target-time (if (numberp beat) (float beat) (rtm beat))))
    (set-current-time target-time)
    (format t "~%[TIMELINE] Track ~A teleported to ~,3fs~%" *current-instrument* target-time)))

(defun sync ()
  (let ((max-time 0.0))
    (maphash (lambda (k trk) (setf max-time (max max-time (track-playhead trk)))) *tracks*)
    (maphash (lambda (k trk) (setf (track-playhead trk) max-time)) *tracks*)
    (format t "~%[TIMELINE] All tracks synchronized to ~,3fs~%" max-time)))

(defun del (n)
  (let ((track-events nil)
        (other-events nil))
    (dolist (event *score*)
      (if (= (getf event :instr) *current-instrument*)
          (push event track-events)
          (push event other-events)))
    (setf track-events (sort track-events #'> :key (lambda (x) (getf x :time))))
    (setf track-events (nthcdr n track-events))
    (setf *score* (append track-events other-events))
    (let ((new-time 0.0))
      (dolist (event track-events)
        (setf new-time (max new-time (+ (getf event :time) (getf event :dur)))))
      (setf (track-playhead (get-current-track)) (float new-time))
      (format t "~%[TIMELINE] Rewound playhead. Deleted ~a events from Track ~a.~%" n *current-instrument*))))

(defun synth (slot-id template-name)
  (let ((template (gethash template-name *synth-templates*)))
    (if template
        (progn
          (setf (gethash slot-id *synth-rack*) template)
          (format t "~%[RACK] Loaded ~A into Slot ~A~%" template-name slot-id))
        (format t "~%[RACK ERROR] No synth template named ~A found in memory.~%" template-name))))

(defun bpm (n)
  (setf *bpm* '())
  (push "t" *bpm*)
  (push 0 *bpm*)
  (push n *bpm*))


;; =============================================================================
;; 9. SYSTEM COMMAND DICTIONARY WRAPPERS
;; =============================================================================

(def-bogu-cmd BPM (:number) (args) (apply #'bpm (expand-vars args)) nil)
(def-bogu-cmd PLAY (&rest :any) (args) (apply #'play (expand-vars args)) nil)
(def-bogu-cmd SAVE (:symbol-optional) (args) (apply #'save args) nil)
(def-bogu-cmd VARS (:symbol-optional) (args) (apply #'vars args) nil)
(def-bogu-cmd WHERE (&rest :any) (args) (apply #'where (expand-vars args)) nil)
(def-bogu-cmd LOOPS (&rest :any) (args) (loops) nil) 
(def-bogu-cmd HELP (:symbol-optional) (args) (apply #'help args) nil)
(def-bogu-cmd RESET (&rest :any) (args) (apply #'reset (expand-vars args)) nil)
(def-bogu-cmd LOAD (:symbol-optional) (args) (apply #'bogu-load args) nil)
(def-bogu-cmd DEL (:number) (args) (apply #'del (expand-vars args)) nil)
(def-bogu-cmd SEEK (:any) (args) (apply #'seek (expand-vars args)) nil)
(def-bogu-cmd SYNC (&rest :any) (args) (apply #'sync (expand-vars args)) nil)
(def-bogu-cmd BANG (&rest :any) (args) (apply #'bang (expand-vars args)) nil)
(def-bogu-cmd SYNTH (:number :symbol) (args) (apply #'synth args) nil)
